name: Publish Snapshot to GitHub Packages

on:
  push:
    branches:
      - dev

#env:
#  GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
#  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
env:
  GITHUB_USERNAME: vladyslav-tertyshnyi-ew
  GITHUB_TOKEN: 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

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3.10.0
        with:
          java-version: 11
          distribution: 'temurin'

      - name: Build and Publish Snapshot
        env:
          USERNAME: ${{ env.GITHUB_USERNAME }}
          TOKEN: ${{ env.GITHUB_TOKEN }}
        run: |
          mvn deploy -DskipTests=true -Dmaven.javadoc.skip=true \
            -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/extrawest/Extrawest-OCA-OCPP \
            -Dusername=${USERNAME} -Dpassword=${TOKEN}